#!/bin/sh
#
# Builds the mechanized model of the kernel's checking judgment (formal/coq,
# docs/KERNEL.md 17) and requires every theorem Audit.v names to rest on no
# axiom and no admitted proof (TRUST.md TCB-META-003).
#
#   tools/formal/check.sh [build directory]
#
# The sources are compiled in a copy under the build directory, so the source
# tree gains no Coq output.

set -eu

root=$(cd "$(dirname "$0")/../.." && pwd)
out="${1:-${root}/build/formal}"
coqc="${COQC:-coqc}"

if ! command -v "${coqc}" >/dev/null 2>&1; then
    echo "coqc not found; install Coq 8.18 or set COQC" >&2
    exit 1
fi

mkdir -p "${out}"
cp "${root}"/formal/coq/*.v "${out}/"
cd "${out}"

"${coqc}" --version

for module in Syntax Semantics Typing Checker Normalize Consistency Certificate Linear; do
    "${coqc}" -Q . CppL "${module}.v"
done

# The kernel's normalization edge table (tests/kernel/normalization_edges.tsv),
# which kernel_normalization_edges_test checks of the kernel, stated of the
# model's normalizer: each row an Example proven by computation, whose
# variables (vN) stand for any value.
awk -F '\t' '
    function ty(name) { return substr(name, 2) " " (substr(name, 1, 1) == "i" ? "true" : "false") }
    function lit(written,    parts, value) {
        split(written, parts, ":")
        if (substr(parts[1], 1, 1) == "v") return "(Var " substr(parts[1], 2) ")"
        value = parts[2]
        if (substr(value, 1, 1) == "-") value = "(" value ")"
        return "(Lit " ty(parts[1]) " " value ")"
    }
    BEGIN {
        op["AddWrap"] = "AddWrap"; op["SubWrap"] = "SubWrap"; op["MulWrap"] = "MulWrap"
        op["Equal"] = "OEq"; op["NotEqual"] = "ONe"; op["Less"] = "OLt"; op["LessEqual"] = "OLe"
        op["Greater"] = "OGt"; op["GreaterEqual"] = "OGe"; op["Not"] = "ONot"; op["Select"] = "OSelect"
        op["AddFits"] = "AddFits"; op["SubFits"] = "SubFits"; op["MulFits"] = "MulFits"
        op["Quotient"] = "OQuot"; op["Remainder"] = "ORem"; op["Convert"] = "OConvert"
        print "(* Generated by tools/formal/check.sh from tests/kernel/normalization_edges.tsv. *)"
        print "From Coq Require Import ZArith List."
        print "Import ListNotations."
        print "From CppL Require Import Syntax Normalize."
        print "Open Scope Z_scope."
        print "Definition closed_nf : term -> term := nf (fun _ => None) (fun _ => None)."
    }
    /^#/ || NF == 0 { next }
    {
        if (!($1 in op)) { print "unknown primitive " $1 > "/dev/stderr"; exit 1 }
        n = split($3, operands, " ")
        list = ""
        for (i = 1; i <= n; i++) list = list (i > 1 ? "; " : "") lit(operands[i])
        rows++
        printf "Example edge_%d : closed_nf (Prim %s %s [%s]) = %s.\nProof. vm_compute. reflexivity. Qed.\n", rows, op[$1], ty($2), list, lit($4)
    }
    END { if (rows < 140) { print "the edge table has " rows " rows" > "/dev/stderr"; exit 1 } }
' "${root}/tests/kernel/normalization_edges.tsv" > NormalizeEdges.v
"${coqc}" -Q . CppL NormalizeEdges.v
edges=$(grep -c '^Example ' NormalizeEdges.v)

# The kernel's translation edge table (tests/kernel/translation_edges.tsv),
# which kernel_translation_edges_test checks of the kernel, stated of the
# model's translation: each row an Example proven by computation that the
# model builds the stated system, constraint for constraint and in order. A
# constraint is compared as the kernel keeps it, its variables merged, in
# increasing order and with nonzero coefficients.
awk -F '\t' '
    function ty(name) { return substr(name, 2) " " (substr(name, 1, 1) == "i" ? "true" : "false") }
    function num(value) { return substr(value, 1, 1) == "-" ? "(" value ")" : value }
    function term(    token, parts, name, arity, i, args) {
        token = tok[pos++]
        if (token ~ /^v[0-9]+$/) return "(Var " substr(token, 2) ")"
        if (index(token, ":") > 0) { split(token, parts, ":"); return "(Lit " ty(parts[1]) " " num(parts[2]) ")" }
        if (!(token in op)) { print "unknown primitive " token > "/dev/stderr"; exit 1 }
        name = tok[pos++]
        arity = (token == "Not" || token == "Convert") ? 1 : (token == "Select" ? 3 : 2)
        args = ""
        for (i = 1; i <= arity; i++) args = args (i > 1 ? "; " : "") term()
        return "(Prim " op[token] " " ty(name) " [" args "])"
    }
    function prop(text,    name, lhs, rhs) {
        if (text == "False") return "PFalse"
        split(text, tok, " ")
        pos = 1
        name = tok[pos++]
        lhs = term()
        rhs = term()
        return "(PEq (TInt " ty(name) ") " lhs " " rhs ")"
    }
    function constraint(text,    n, parts, i, pair, terms) {
        n = split(text, parts, " ")
        terms = ""
        for (i = 1; i < n; i++) {
            split(parts[i], pair, ":")
            terms = terms (i > 1 ? "; " : "") "(" pair[1] "%nat, " num(pair[2]) ")"
        }
        return "([" terms "], " num(substr(parts[n], 2)) ")"
    }
    function list(text, disjunctive,    n, items, i, out, sides) {
        sub(/^ +/, "", text); sub(/ +$/, "", text)
        if (text == "-") return "[]"
        n = split(text, items, " ; ")
        out = ""
        for (i = 1; i <= n; i++) {
            if (disjunctive) {
                split(items[i], sides, " or ")
                out = out (i > 1 ? "; " : "") "(" constraint(sides[1]) ", " constraint(sides[2]) ")"
            } else {
                out = out (i > 1 ? "; " : "") constraint(items[i])
            }
        }
        return "[" out "]"
    }
    BEGIN {
        op["AddWrap"] = "AddWrap"; op["SubWrap"] = "SubWrap"; op["MulWrap"] = "MulWrap"
        op["Equal"] = "OEq"; op["NotEqual"] = "ONe"; op["Less"] = "OLt"; op["LessEqual"] = "OLe"
        op["Greater"] = "OGt"; op["GreaterEqual"] = "OGe"; op["Not"] = "ONot"; op["Select"] = "OSelect"
        op["AddFits"] = "AddFits"; op["SubFits"] = "SubFits"; op["MulFits"] = "MulFits"
        op["Quotient"] = "OQuot"; op["Remainder"] = "ORem"; op["Convert"] = "OConvert"
        print "(* Generated by tools/formal/check.sh from tests/kernel/translation_edges.tsv. *)"
        print "From Coq Require Import ZArith List Bool."
        print "Import ListNotations."
        print "From CppL Require Import Syntax Normalize Certificate Linear."
        print "Open Scope Z_scope."
        print "Fixpoint ins_term (v : nat) (c : Z) (l : list (nat * Z)) : list (nat * Z) :="
        print "  match l with"
        print "  | [] => [(v, c)]"
        print "  | (v1, c1) :: l1 =>"
        print "      if Nat.eqb v v1 then (v1, c + c1) :: l1"
        print "      else if Nat.ltb v v1 then (v, c) :: l else (v1, c1) :: ins_term v c l1"
        print "  end."
        print "Definition canon (c : constraint) : list (nat * Z) * Z :="
        print "  (filter (fun vc => negb (snd vc =? 0)) (fold_left (fun acc vc => ins_term (fst vc) (snd vc) acc) (terms c) []),"
        print "   constant c)."
        print "Definition translated (G : list ty) (Fs : list prop) (P : prop) :="
        print "  match arithmetic_system (fun _ => None) (fun _ => None) G max_linear_depth Fs P with"
        print "  | Some s => Some (nvars s, map canon (constraints s), map (fun d => (canon (fst d), canon (snd d))) (disjunctions s))"
        print "  | None => None"
        print "  end."
    }
    /^#/ || NF == 0 { next }
    {
        if (NF != 4) { print "a translation row has " NF " fields" > "/dev/stderr"; exit 1 }
        locals = ""
        if ($1 != "-") {
            n = split($1, names, " ")
            for (i = n; i >= 1; i--) locals = locals (i < n ? "; " : "") "TInt " ty(names[i])
        }
        facts = ""
        if ($2 != "-") {
            n = split($2, items, ";")
            for (i = 1; i <= n; i++) {
                item = items[i]; sub(/^ +/, "", item); sub(/ +$/, "", item)
                facts = facts (i > 1 ? "; " : "") prop(item)
            }
        }
        goal = prop($3)
        split($4, built, "[|]")
        count = built[1]; gsub(/ /, "", count)
        rows++
        printf "Example translation_%d : translated [%s] [%s] %s = Some (%s%%nat, %s, %s).\nProof. vm_compute. reflexivity. Qed.\n", rows, locals, facts, goal, count, list(built[2], 0), list(built[3], 1)
    }
    END { if (rows < 80) { print "the translation table has " rows " rows" > "/dev/stderr"; exit 1 } }
' "${root}/tests/kernel/translation_edges.tsv" > TranslationEdges.v
"${coqc}" -Q . CppL TranslationEdges.v
translations=$(grep -c '^Example ' TranslationEdges.v)

# The kernel's rule table (tests/kernel/check_edges.tsv), which
# kernel_check_edges_test checks of the kernel, stated of the model's checker:
# each row an Example proven by computation that the model's check, with its
# normalizer and its arithmetic, gives the row's verdict.
awk -F '\t' '
    function ty(name) { return "(TInt " substr(name, 2) " " (substr(name, 1, 1) == "i" ? "true" : "false") ")" }
    function bare(name) { return substr(name, 2) " " (substr(name, 1, 1) == "i" ? "true" : "false") }
    function num(value) { return substr(value, 1, 1) == "-" ? "(" value ")" : value }
    function fail(message) { print message > "/dev/stderr"; failed = 1; exit 1 }
    function term(    token, parts, name, arity, i, args) {
        token = tok[pos++]
        if (token ~ /^v[0-9]+$/) return "(Var " substr(token, 2) ")"
        if (index(token, ":") > 0) { split(token, parts, ":"); return "(Lit " bare(parts[1]) " " num(parts[2]) ")" }
        if (!(token in op)) fail("unknown primitive " token)
        name = tok[pos++]
        arity = (token == "Not" || token == "Convert") ? 1 : (token == "Select" ? 3 : 2)
        args = ""
        for (i = 1; i <= arity; i++) args = args (i > 1 ? "; " : "") term()
        return "(Prim " op[token] " " bare(name) " [" args "])"
    }
    function prop(    token, name, a, b) {
        token = tok[pos++]
        if (token == "eq") { name = tok[pos++]; a = term(); b = term(); return "(PEq " ty(name) " " a " " b ")" }
        if (token == "all") { name = tok[pos++]; a = prop(); return "(PAll " ty(name) " " a ")" }
        if (token == "imp") { a = prop(); b = prop(); return "(PImp " a " " b ")" }
        if (token == "and") { a = prop(); b = prop(); return "(PAnd " a " " b ")" }
        if (token == "or") { a = prop(); b = prop(); return "(POr " a " " b ")" }
        if (token == "false") return "PFalse"
        fail("unknown proposition " token)
    }
    function side(    token) {
        token = tok[pos++]
        if (token != "left" && token != "right") fail("unknown side " token)
        return token == "right" ? "true" : "false"
    }
    function pairs(n,    i, pair, out) {
        out = ""
        for (i = 1; i <= n; i++) { split(tok[pos++], pair, ":"); out = out (i > 1 ? "; " : "") "(" pair[1] "%nat, " num(pair[2]) ")" }
        return "[" out "]"
    }
    function cert(    token, n, items, k, a, b) {
        token = tok[pos++]
        if (token == "farkas") { n = tok[pos++]; return "(FarkasSum " pairs(n) ")" }
        if (token == "split") { n = tok[pos++]; items = pairs(n); k = num(tok[pos++]); a = cert(); b = cert(); return "(IntegerSplit " items " " k " " a " " b ")" }
        if (token == "cases") { n = tok[pos++]; a = cert(); b = cert(); return "(DisjunctionCases " n " " a " " b ")" }
        fail("unknown certificate " token)
    }
    function evid(    token, name, a, b, c, p, e1, e2, e3, n, i, facts, k) {
        token = tok[pos++]
        if (token == "refl") return "ERefl"
        if (token == "alli") { name = tok[pos++]; e1 = evid(); return "(EAllI " ty(name) " " e1 ")" }
        if (token == "alle") { p = prop(); e1 = evid(); a = term(); return "(EAllE " p " " e1 " " a ")" }
        if (token == "hyp") return "(EHyp " tok[pos++] ")"
        if (token == "impi") { p = prop(); e1 = evid(); return "(EImpI " p " " e1 ")" }
        if (token == "impe") { p = prop(); e1 = evid(); e2 = evid(); return "(EImpE " p " " e1 " " e2 ")" }
        if (token == "eqe") { name = tok[pos++]; a = term(); b = term(); p = prop(); e1 = evid(); e2 = evid(); return "(EEqE " ty(name) " " a " " b " " p " " e1 " " e2 ")" }
        if (token == "cond") { name = tok[pos++]; a = term(); b = term(); c = term(); p = prop(); e1 = evid(); e2 = evid(); return "(ECond " ty(name) " " a " " b " " c " " p " " e1 " " e2 ")" }
        if (token == "lin") {
            n = tok[pos++]
            facts = ""
            for (i = 1; i <= n; i++) { p = prop(); e1 = evid(); facts = facts (i > 1 ? "; " : "") "(" p ", " e1 ")" }
            k = cert()
            return "(ELin [" facts "] " k ")"
        }
        if (token == "andi") { e1 = evid(); e2 = evid(); return "(EAndI " e1 " " e2 ")" }
        if (token == "ande") { p = prop(); e1 = evid(); return "(EAndE " p " " e1 " " side() ")" }
        if (token == "ori") { e1 = evid(); return "(EOrI " e1 " " side() ")" }
        if (token == "ore") { p = prop(); e1 = evid(); e2 = evid(); e3 = evid(); return "(EOrE " p " " e1 " " e2 " " e3 ")" }
        if (token == "falsee") { e1 = evid(); return "(EFalseE " e1 ")" }
        if (token == "ind") { name = tok[pos++]; e1 = evid(); e2 = evid(); return "(EInd " ty(name) " " e1 " " e2 ")" }
        fail("unknown evidence " token)
    }
    BEGIN {
        op["AddWrap"] = "AddWrap"; op["SubWrap"] = "SubWrap"; op["MulWrap"] = "MulWrap"
        op["Equal"] = "OEq"; op["NotEqual"] = "ONe"; op["Less"] = "OLt"; op["LessEqual"] = "OLe"
        op["Greater"] = "OGt"; op["GreaterEqual"] = "OGe"; op["Not"] = "ONot"; op["Select"] = "OSelect"
        op["AddFits"] = "AddFits"; op["SubFits"] = "SubFits"; op["MulFits"] = "MulFits"
        op["Quotient"] = "OQuot"; op["Remainder"] = "ORem"; op["Convert"] = "OConvert"
        print "(* Generated by tools/formal/check.sh from tests/kernel/check_edges.tsv. *)"
        print "From Coq Require Import ZArith List Bool."
        print "Import ListNotations."
        print "From CppL Require Import Syntax Checker Normalize Certificate Linear."
        print "Open Scope Z_scope."
        print "Arguments ERefl {cert}. Arguments EAllI {cert}. Arguments EAllE {cert}. Arguments EHyp {cert}."
        print "Arguments EImpI {cert}. Arguments EImpE {cert}. Arguments EEqE {cert}. Arguments ECond {cert}."
        print "Arguments ELin {cert}. Arguments EAndI {cert}. Arguments EAndE {cert}. Arguments EOrI {cert}."
        print "Arguments EOrE {cert}. Arguments EFalseE {cert}. Arguments EInd {cert}."
        print "Definition closed_check : prop -> evid certificate -> bool :="
        print "  check (fun _ => None) (nf (fun _ => None) (fun _ => None)) certificate (lin_ok (fun _ => None) (fun _ => None))."
    }
    /^#/ || NF == 0 { next }
    {
        if (NF != 3) fail("a rule row has " NF " fields")
        if ($3 != "accept" && $3 != "refuse") fail("unknown verdict " $3)
        split($1, tok, " "); pos = 1; goal = prop()
        split($2, tok, " "); pos = 1; evidence = evid()
        rows++
        if ($3 == "accept") accepted++
        printf "Example check_%d : closed_check %s %s = %s.\nProof. vm_compute. reflexivity. Qed.\n", rows, goal, evidence, ($3 == "accept" ? "true" : "false")
    }
    END {
        if (failed) exit 1
        if (rows < 60 || accepted < 25) { print "the rule table has " rows " rows, " accepted " accepted" > "/dev/stderr"; exit 1 }
    }
' "${root}/tests/kernel/check_edges.tsv" > CheckEdges.v
"${coqc}" -Q . CppL CheckEdges.v
rules=$(grep -c '^Example ' CheckEdges.v)

"${coqc}" -Q . CppL Audit.v > audit.txt
cat audit.txt

theorems=$(grep -c '^Print Assumptions' Audit.v)
closed=$(grep -c '^Closed under the global context$' audit.txt || true)
if [ "${closed}" != "${theorems}" ]; then
    echo "error: ${theorems} theorems are audited and ${closed} rest on nothing but Coq's kernel" >&2
    exit 1
fi

# No proof may be left unfinished.
if grep -nE '\b(Admitted|admit|Axiom|Parameter|Conjecture)\b' "${root}"/formal/coq/*.v; then
    echo "error: the model contains an axiom or an unfinished proof" >&2
    exit 1
fi

echo "formal model: ${theorems} theorems checked, none resting on an axiom; ${edges} normalization edges, ${translations} translations and ${rules} verdicts computed"
