#!/bin/sh
#
# Builds the mechanized model of the kernel's checking judgment (formal/coq,
# docs/KERNEL.md 17) and requires every theorem Audit.v names to rest on no
# axiom and no admitted proof (TRUST.md TCB-META-003).
#
#   tools/formal/check.sh [build directory]
#
# The sources are compiled in a copy under the build directory, so the source
# tree gains no Coq output.

set -eu

root=$(cd "$(dirname "$0")/../.." && pwd)
out="${1:-${root}/build/formal}"
coqc="${COQC:-coqc}"

if ! command -v "${coqc}" >/dev/null 2>&1; then
    echo "coqc not found; install Coq 8.18 or set COQC" >&2
    exit 1
fi

mkdir -p "${out}"
cp "${root}"/formal/coq/*.v "${out}/"
cd "${out}"

"${coqc}" --version

for module in Syntax Semantics Typing Checker Normalize Consistency Certificate; do
    "${coqc}" -Q . CppL "${module}.v"
done

# The kernel's normalization edge table (tests/kernel/normalization_edges.tsv),
# which kernel_normalization_edges_test checks of the kernel, stated of the
# model's normalizer: each row an Example proven by computation, whose
# variables (vN) stand for any value.
awk -F '\t' '
    function ty(name) { return substr(name, 2) " " (substr(name, 1, 1) == "i" ? "true" : "false") }
    function lit(written,    parts, value) {
        split(written, parts, ":")
        if (substr(parts[1], 1, 1) == "v") return "(Var " substr(parts[1], 2) ")"
        value = parts[2]
        if (substr(value, 1, 1) == "-") value = "(" value ")"
        return "(Lit " ty(parts[1]) " " value ")"
    }
    BEGIN {
        op["AddWrap"] = "AddWrap"; op["SubWrap"] = "SubWrap"; op["MulWrap"] = "MulWrap"
        op["Equal"] = "OEq"; op["NotEqual"] = "ONe"; op["Less"] = "OLt"; op["LessEqual"] = "OLe"
        op["Greater"] = "OGt"; op["GreaterEqual"] = "OGe"; op["Not"] = "ONot"; op["Select"] = "OSelect"
        op["AddFits"] = "AddFits"; op["SubFits"] = "SubFits"; op["MulFits"] = "MulFits"
        op["Quotient"] = "OQuot"; op["Remainder"] = "ORem"; op["Convert"] = "OConvert"
        print "(* Generated by tools/formal/check.sh from tests/kernel/normalization_edges.tsv. *)"
        print "From Coq Require Import ZArith List."
        print "Import ListNotations."
        print "From CppL Require Import Syntax Normalize."
        print "Open Scope Z_scope."
        print "Definition closed_nf : term -> term := nf (fun _ => None) (fun _ => None)."
    }
    /^#/ || NF == 0 { next }
    {
        if (!($1 in op)) { print "unknown primitive " $1 > "/dev/stderr"; exit 1 }
        n = split($3, operands, " ")
        list = ""
        for (i = 1; i <= n; i++) list = list (i > 1 ? "; " : "") lit(operands[i])
        rows++
        printf "Example edge_%d : closed_nf (Prim %s %s [%s]) = %s.\nProof. vm_compute. reflexivity. Qed.\n", rows, op[$1], ty($2), list, lit($4)
    }
    END { if (rows < 140) { print "the edge table has " rows " rows" > "/dev/stderr"; exit 1 } }
' "${root}/tests/kernel/normalization_edges.tsv" > NormalizeEdges.v
"${coqc}" -Q . CppL NormalizeEdges.v
edges=$(grep -c '^Example ' NormalizeEdges.v)

"${coqc}" -Q . CppL Audit.v > audit.txt
cat audit.txt

theorems=$(grep -c '^Print Assumptions' Audit.v)
closed=$(grep -c '^Closed under the global context$' audit.txt || true)
if [ "${closed}" != "${theorems}" ]; then
    echo "error: ${theorems} theorems are audited and ${closed} rest on nothing but Coq's kernel" >&2
    exit 1
fi

# No proof may be left unfinished.
if grep -nE '\b(Admitted|admit|Axiom|Parameter|Conjecture)\b' "${root}"/formal/coq/*.v; then
    echo "error: the model contains an axiom or an unfinished proof" >&2
    exit 1
fi

echo "formal model: ${theorems} theorems checked, none resting on an axiom; ${edges} normalization edges computed"
