# Computes the verifier semantics digest (cmake/VerifierSemanticsSources.cmake).
#
#   cmake -DROOT=<source root> [-DHEADER=<generated header>] [-DSTAMP=<stamp file>]
#         [-DDIGEST_FILE=<file>] -P ComputeVerifierSemantics.cmake
#
# The digest is SHA-256 over a canonical text: a version line, then one line per
# semantic source in byte order of its root-relative path, holding that path and
# the SHA-256 of the file's content with every CRLF read as LF. So the same
# sources give the same digest wherever they are checked out, whenever their
# files were touched, and whatever line endings a checkout gave them; any change
# to a byte of one, or a file added to or removed from one of those components,
# gives another.
#
# HEADER is written only when its content would change, so a rebuild that
# changes nothing recompiles nothing; STAMP is always touched, for the build to
# know the digest is current. DIGEST_FILE receives the digest alone, for tests.

cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED ROOT)
    message(FATAL_ERROR "ComputeVerifierSemantics.cmake needs -DROOT=<source root>")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/VerifierSemanticsSources.cmake")

cppl_component_sources("${ROOT}" "${CPPL_SEMANTIC_COMPONENTS}" sources)
list(LENGTH sources count)
if(count EQUAL 0)
    message(FATAL_ERROR "no semantic source was found under '${ROOT}'")
endif()

# Semantic configuration: a compile-time switch that changes what the verifier
# decides would be named here. There is none today; the line keeps the place.
set(canonical "cppl-verifier-semantics-digest-v1\nconfiguration none\n")
foreach(relative IN LISTS sources)
    file(READ "${ROOT}/${relative}" content)
    string(REPLACE "\r\n" "\n" content "${content}")
    string(SHA256 file_digest "${content}")
    string(APPEND canonical "file ${relative} ${file_digest}\n")
endforeach()
string(SHA256 digest "${canonical}")

if(DEFINED DIGEST_FILE)
    file(WRITE "${DIGEST_FILE}" "${digest}\n")
endif()

if(DEFINED HEADER)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " bytes "${digest}")
    string(REGEX REPLACE ", $" "" bytes "${bytes}")
    set(text "// Generated by cmake/ComputeVerifierSemantics.cmake. Do not edit.\n")
    string(APPEND text "//\n// The verifier semantics digest of the sources this compiler was built from\n")
    string(APPEND text "// (cmake/VerifierSemanticsSources.cmake, TRUST.md TCB-XTU-008): ${digest}\n")
    string(APPEND text "#pragma once\n\n#include <array>\n#include <cstdint>\n\n")
    string(APPEND text "namespace cppl::driver {\n\n")
    string(APPEND text "inline constexpr std::array<std::uint8_t, 32> kVerifierSemanticsDigest{\n    ${bytes}};\n\n")
    string(APPEND text "} // namespace cppl::driver\n")
    set(previous "")
    if(EXISTS "${HEADER}")
        file(READ "${HEADER}" previous)
    endif()
    if(NOT previous STREQUAL text)
        file(WRITE "${HEADER}" "${text}")
    endif()
endif()

if(DEFINED STAMP)
    file(TOUCH "${STAMP}")
endif()
