# The source identity of a build (TRUST.md TCB-REPRO-001, TCB-VERSION-004).
#
# `cppl --cppl-version` names the source a compiler was built from, so a
# release can be traced to the commit it came from and a clean checkout of
# that commit or its tag reproduces the same record. What is recorded:
#
#   - the commit the tree is at, as Git names it, or `unknown` where the tree
#     is not a Git work tree or Git is not available;
#   - the release tag at that commit, or `none`;
#   - whether a tracked file differs from that commit: `clean`, `modified`
#     or `unknown`. Untracked files are not source and take no part.
#
# Nothing else is: no time, no user, no host, no path. Two builds of one commit
# record the same identity wherever and whenever they are made.
#
# Run as a script at build time, with CPPL_SOURCE_ROOT, CPPL_GIT (empty when
# Git was not found) and CPPL_OUTPUT. The header is rewritten only when its
# content would change, so a build whose identity did not move compiles
# nothing again.

if(NOT CPPL_SOURCE_ROOT OR NOT CPPL_OUTPUT)
    message(FATAL_ERROR "CPPL_SOURCE_ROOT and CPPL_OUTPUT name the tree and where its identity is written")
endif()

set(revision "unknown")
set(tag "none")
set(tree "unknown")

if(CPPL_GIT)
    execute_process(
        COMMAND "${CPPL_GIT}" -C "${CPPL_SOURCE_ROOT}" rev-parse --verify HEAD
        RESULT_VARIABLE status
        OUTPUT_VARIABLE head
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(status EQUAL 0 AND head MATCHES "^[0-9a-f]+$")
        set(revision "${head}")

        execute_process(
            COMMAND "${CPPL_GIT}" -C "${CPPL_SOURCE_ROOT}" describe --tags --exact-match HEAD
            RESULT_VARIABLE status
            OUTPUT_VARIABLE exact
            ERROR_QUIET
            OUTPUT_STRIP_TRAILING_WHITESPACE)
        # A tag name is a refname; only the characters a release tag uses are
        # carried into a C++ string literal.
        if(status EQUAL 0 AND exact MATCHES "^[0-9A-Za-z._+-]+$")
            set(tag "${exact}")
        endif()

        # --no-optional-locks: reading the state must never contend with a Git
        # command the developer is running at the same time.
        execute_process(
            COMMAND "${CPPL_GIT}" --no-optional-locks -C "${CPPL_SOURCE_ROOT}" status --porcelain
                    --untracked-files=no
            RESULT_VARIABLE status
            OUTPUT_VARIABLE changes
            ERROR_QUIET)
        if(status EQUAL 0)
            if(changes STREQUAL "")
                set(tree "clean")
            else()
                set(tree "modified")
            endif()
        endif()
    endif()
endif()

set(header "#pragma once\n\n#include <string_view>\n\nnamespace cppl::driver {\n\n")
string(APPEND header "// Generated by cmake/SourceIdentity.cmake. Do not edit.\n")
string(APPEND header "inline constexpr std::string_view kSourceRevision = \"${revision}\";\n")
string(APPEND header "inline constexpr std::string_view kSourceTag = \"${tag}\";\n")
string(APPEND header "inline constexpr std::string_view kSourceTree = \"${tree}\";\n\n")
string(APPEND header "} // namespace cppl::driver\n")

set(current "")
if(EXISTS "${CPPL_OUTPUT}")
    file(READ "${CPPL_OUTPUT}" current)
endif()
if(NOT current STREQUAL header)
    file(WRITE "${CPPL_OUTPUT}" "${header}")
endif()
