# The verifier-semantics digest (SPEC.md TUBOUND-005, TRUST.md TCB-XTU-008).
#
# A verification interface is bound to the semantics of the verifier that
# wrote it. A declared version names that semantics, but nothing forces it to
# change when the code does, so the interface is also bound to a digest of
# every source that can change what the verifier concludes: each file of the
# semantics-bearing set, by its path relative to the source root and by its
# content. Timestamps, absolute paths, documentation and the bytes of the
# built executable take no part, so two builds of one source tree agree and
# any edit to that code changes the digest.
#
# The set is every C++ source and build description under `kernel/`, `vir/`,
# `clang/` and `compiler/`, except `compiler/formatter/`, which only lays out
# source text.
#
# Included, this defines the functions below. Run as a script it computes the
# digest of CPPL_SOURCE_ROOT and either writes the header CPPL_OUTPUT, only
# when its content would change, touching CPPL_STAMP, or prints the digest
# when CPPL_PRINT is set.

function(cppl_verifier_semantics_sources root out_var)
    # A file added to the set must reach the build's dependency list too.
    set(rescan "")
    if(NOT CMAKE_SCRIPT_MODE_FILE)
        set(rescan CONFIGURE_DEPENDS)
    endif()
    file(GLOB_RECURSE candidates ${rescan}
        LIST_DIRECTORIES false
        RELATIVE "${root}"
        "${root}/kernel/*"
        "${root}/vir/*"
        "${root}/clang/*"
        "${root}/compiler/*")
    set(selected "")
    foreach(candidate IN LISTS candidates)
        if(candidate MATCHES "^compiler/formatter/")
            continue()
        endif()
        if(candidate MATCHES "\\.(cpp|hpp|h|inc|def)$" OR candidate MATCHES "(^|/)CMakeLists\\.txt$")
            list(APPEND selected "${candidate}")
        endif()
    endforeach()
    list(SORT selected)
    set(${out_var} "${selected}" PARENT_SCOPE)
endfunction()

function(cppl_verifier_semantics_digest root out_var)
    cppl_verifier_semantics_sources("${root}" files)
    list(LENGTH files count)
    if(count EQUAL 0)
        message(FATAL_ERROR "no semantics-bearing source was found under '${root}'")
    endif()
    set(manifest "cppl-verifier-semantics-v1\n")
    foreach(file IN LISTS files)
        file(SHA256 "${root}/${file}" content)
        string(APPEND manifest "${file}\n${content}\n")
    endforeach()
    string(SHA256 digest "${manifest}")
    set(${out_var} "${digest}" PARENT_SCOPE)
endfunction()

if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    if(NOT CPPL_SOURCE_ROOT)
        message(FATAL_ERROR "CPPL_SOURCE_ROOT names no source tree")
    endif()
    cppl_verifier_semantics_digest("${CPPL_SOURCE_ROOT}" digest)
    if(CPPL_PRINT)
        message("${digest}")
        return()
    endif()
    if(NOT CPPL_OUTPUT OR NOT CPPL_STAMP)
        message(FATAL_ERROR "CPPL_OUTPUT and CPPL_STAMP name where the digest is written")
    endif()
    set(header "#pragma once\n\n#include <string_view>\n\nnamespace cppl::driver {\n\n")
    string(APPEND header "// Generated by cmake/VerifierSemantics.cmake. Do not edit.\n")
    string(APPEND header "inline constexpr std::string_view kVerifierSemanticsDigest = \"${digest}\";\n\n")
    string(APPEND header "} // namespace cppl::driver\n")
    set(current "")
    if(EXISTS "${CPPL_OUTPUT}")
        file(READ "${CPPL_OUTPUT}" current)
    endif()
    if(NOT current STREQUAL header)
        file(WRITE "${CPPL_OUTPUT}" "${header}")
    endif()
    file(TOUCH "${CPPL_STAMP}")
endif()
